name: Deploy to Amazon ECS

on:
  push:
    branches:
      - "main"

env:
  AWS_REGION: us-east-2                 
  ECR_REPOSITORY: my-first-ecr-repo          
  DEV_ECS_SERVICE: dev-ecs-service               
  DEV_ECS_CLUSTER: dev-cluster
  STAGE_ECS_SERVICE: stage-ecs-service               
  STAGE_ECS_CLUSTER: stage-cluster
  PROD_ECS_SERVICE: prod-ecs-service               
  PROD_ECS_CLUSTER: prod-cluster                  
  ECS_TASK_DEFINITION: .github/workflows/task-definition.json
  CONTAINER_NAME: my-first-task           

permissions:
  id-token: write
  contents: read 
  
jobs:
  build-and-release:
    name: Continuous Integration
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: codebase/rdicidr-0.1.0

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 15 
        path: codebase/rdicidr-0.1.0

    - name: Install NPM dependencies
      run: npm install 
      working-directory: codebase/rdicidr-0.1.0

    - name: Build project assets
      run: npm run build
      working-directory: codebase/rdicidr-0.1.0

      #- name: Build
      #  run: npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::893688252992:role/Github
        role-session-name: Github
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: "true"

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG_LATEST: latest
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_LATEST -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./codebase/rdicidr-0.1.0/
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_LATEST
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

  deploy-to-dev:
    name: dev-env
    runs-on: ubuntu-latest
    needs: build-and-release

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::893688252992:role/Github
        role-session-name: Github
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Deploy to dev
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION }}
        service: ${{ env.DEV_ECS_SERVICE }}
        cluster: ${{ env.DEV_ECS_CLUSTER }}
        wait-for-service-stability: true

  deploy-to-stage:
    name: staging-env
    runs-on: ubuntu-latest
    needs: deploy-to-dev

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::893688252992:role/Github
        role-session-name: Github
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Deploy to Stage
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION }}
        service: ${{ env.STAGE_ECS_SERVICE }}
        cluster: ${{ env.STAGE_ECS_CLUSTER }}
        wait-for-service-stability: true

  deploy-to-prod:
    name: prod-env
    runs-on: ubuntu-latest
    needs: deploy-to-stage

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::893688252992:role/Github
        role-session-name: Github
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Deploy to Prod
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION }}
        service: ${{ env.PROD_ECS_SERVICE }}
        cluster: ${{ env.PROD_ECS_CLUSTER }}
        wait-for-service-stability: true


